# Generated by Django 5.2.14 on 2026-05-07 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Microcontroller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microcontrollers', to='communities.community')),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity_liters', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('current_level_pct', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico'), ('OVERFLOW', 'Desbordamiento')], default='NORMAL', max_length=20)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanks', to='communities.household')),
                ('microcontroller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='devices.microcontroller')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('ULTRASONIC', 'Ultrasónico'), ('FLOW', 'Flujo de Agua'), ('PH', 'pH'), ('TEMPERATURE', 'Temperatura')], max_length=20)),
                ('pin', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='devices.tank')),
            ],
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('is_open', models.BooleanField(default=False)),
                ('last_toggled', models.DateTimeField(blank=True, null=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valves', to='devices.tank')),
                ('toggled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
