# Generated by Django 5.2.14 on 2026-05-07 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevelReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_pct', models.FloatField()),
                ('distance_cm', models.FloatField()),
                ('volume_liters', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.sensor')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.tank')),
            ],
            options={
                'indexes': [models.Index(fields=['sensor', 'timestamp'], name='telemetry_w_sensor__4732c3_idx'), models.Index(fields=['tank', 'timestamp'], name='telemetry_w_tank_id_d6bb1d_idx')],
            },
        ),
    ]
