# Generated by Django 5.2.14 on 2026-05-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('OVERFLOW', 'Desbordamiento'), ('CRITICAL_LOW', 'Nivel Crítico Bajo'), ('SENSOR_FAIL', 'Falla de Sensor'), ('DEVICE_OFFLINE', 'Dispositivo Desconectado'), ('VALVE_STUCK', 'Válvula Atascada'), ('BATTERY_LOW', 'Batería Baja')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítica')], max_length=10)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
