# Generated by Django 5.2.14 on 2026-05-07 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='communities.community'),
        ),
        migrations.AddField(
            model_name='household',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to=settings.AUTH_USER_MODEL),
        ),
    ]
