# Generated by Django 5.2.13 on 2026-05-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='name',
            field=models.CharField(default='Vivienda', max_length=200),
        ),
    ]
